biz1 = Biz.find_by_name('Cocobang')
biz2 = Biz.find_by_name('Homeroom')
biz3 = Biz.find_by_name('Ushi Taro')
biz4 = Biz.find_by_name('Mensho Tokyo')
biz5 = Biz.find_by_name('Boba Guys')
biz6 = Biz.find_by_name('Urban Rital')
biz7 = Biz.find_by_name("Ryoko's")
biz8 = Biz.find_by_name('Saru Sushi Bar')
spa_vitale = Biz.find_by_name('Spa Vitale')
burke = Biz.find_by_name('Burke Williams Day Spa')
qua = Biz.find_by_name('Qua The Spa at SOMA GRAND')
nob = Biz.find_by_name('Nob Hill Spa')
pure = Biz.find_by_name('Pure Organic Spa')
kabuki = Biz.find_by_name('Kabuki Springs & Spa')
earthbody = Biz.find_by_name('Earthbody')
little_sweet = Biz.find_by_name('Little Sweet')
quali = Biz.find_by_name('QualiTea')
teaspoon = Biz.find_by_name('Teaspoon')
identitea = Biz.find_by_name('Indentitea')
itea = Biz.find_by_name('i-Tea')
teahut = Biz.find_by_name("Tea Hut")
alchemist = Biz.find_by_name("Alchemist Bar & Lounge")
beer_pong = Biz.find_by_name("The Beer Pong Lounge")
f8 = Biz.find_by_name("F8 Nightclub and Bar")
view_lounge = Biz.find_by_name("The View Lounge")
monroe = Biz.find_by_name("Monroe")
b_pati = Biz.find_by_name("B Patisserie")
tartine = Biz.find_by_name("Tartine Bakery & Cafe")
holmes = Biz.find_by_name("Mr Holmes Bakehouse")
golden = Biz.find_by_name("Golden Gate Bakery")
schubert = Biz.find_by_name("Schubert’s Bakery")
craftsman = Biz.find_by_name("Craftsman and Wolves")

day_spas = Tag.create!(name: 'Day Spas')
skin_care = Tag.create!(name: 'Skin Care')
massage = Tag.create!(name: 'Massage')
eyelash = Tag.create!(name: 'Eyelash Service')
permanent_makeup = Tag.create!(name: 'Permanent Makeup')
korean = Tag.create!(name: 'Korean')
ramen = Tag.create!(name: 'Ramen')
american = Tag.create!(name: 'American (Traditional)')
noddles = Tag.create!(name: 'Noodles')
coffee_tea = Tag.create!(name: 'Coffee')
bubble_tea = Tag.create!(name: 'Bubble Tea')
cafes = Tag.create!(name: 'Cafes')
sushi_bars = Tag.create!(name: 'Sushi Bars')
japaness = Tag.create!(name: 'Japaness')
seafood = Tag.create!(name: 'Seafood')
desserts = Tag.create!(name: 'Desserts')
tea_rooms = Tag.create!(name: 'Tea Rooms')
lounges = Tag.create!(name: 'Lounges')
cocktail = Tag.create!(name: 'Cocktail Bars')
sport_bars = Tag.create!(name: 'Sports Bars')
dance_club = Tag.create!(name: 'Dance Clubs')
beer = Tag.create!(name: 'Beer')
bakeries = Tag.create!(name: 'Bakeries')
macarons = Tag.create!(name: 'Macarons')

Tagging.create!(tag_id: bakeries.id, biz_id: craftsman.id)
Tagging.create!(tag_id: cafes.id, biz_id: craftsman.id)
Tagging.create!(tag_id: bakeries.id, biz_id: schubert.id)
Tagging.create!(tag_id: desserts.id, biz_id: schubert.id)
Tagging.create!(tag_id: bakeries.id, biz_id: golden.id)
Tagging.create!(tag_id: bakeries.id, biz_id: holmes.id)
Tagging.create!(tag_id: bakeries.id, biz_id: tartine.id)
Tagging.create!(tag_id: desserts.id, biz_id: tartine.id)
Tagging.create!(tag_id: cafes.id, biz_id: tartine.id)
Tagging.create!(tag_id: bakeries.id, biz_id: b_pati.id)
Tagging.create!(tag_id: macarons.id, biz_id: b_pati.id)
Tagging.create!(tag_id: lounges.id, biz_id: monroe.id)
Tagging.create!(tag_id: dance_club.id, biz_id: monroe.id)
Tagging.create!(tag_id: lounges.id, biz_id: view_lounge.id)
Tagging.create!(tag_id: beer.id, biz_id: view_lounge.id)
Tagging.create!(tag_id: lounges.id, biz_id: f8.id)
Tagging.create!(tag_id: dance_club.id, biz_id: f8.id)
Tagging.create!(tag_id: lounges.id, biz_id: beer_pong.id)
Tagging.create!(tag_id: sport_bars.id, biz_id: beer_pong.id)
Tagging.create!(tag_id: lounges.id, biz_id: alchemist.id)
Tagging.create!(tag_id: cocktail.id, biz_id: alchemist.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: teahut.id)
Tagging.create!(tag_id: tea_rooms.id, biz_id: teahut.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: identitea.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: itea.id)
Tagging.create!(tag_id: desserts.id, biz_id: itea.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: teaspoon.id)
Tagging.create!(tag_id: desserts.id, biz_id: teaspoon.id)
Tagging.create!(tag_id: tea_rooms.id, biz_id: teaspoon.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: quali.id)
Tagging.create!(tag_id: bubble_tea.id, biz_id: little_sweet.id)
Tagging.create!(tag_id: coffee_tea.id, biz_id: little_sweet.id)
Tagging.create!(tag_id: day_spas.id, biz_id: spa_vitale.id)
Tagging.create!(tag_id: day_spas.id, biz_id: burke.id)
Tagging.create!(tag_id: skin_care.id, biz_id: burke.id)
Tagging.create!(tag_id: massage.id, biz_id: burke.id)
Tagging.create!(tag_id: day_spas.id, biz_id: qua.id)
Tagging.create!(tag_id: eyelash.id, biz_id: qua.id)
Tagging.create!(tag_id: permanent_makeup.id, biz_id: qua.id)
Tagging.create!(tag_id: day_spas.id, biz_id: nob.id)
Tagging.create!(tag_id: day_spas.id, biz_id: pure.id)
Tagging.create!(tag_id: massage.id, biz_id: pure.id)
Tagging.create!(tag_id: skin_care.id, biz_id: pure.id)
Tagging.create!(tag_id: day_spas.id, biz_id: kabuki.id)
Tagging.create!(tag_id: day_spas.id, biz_id: earthbody.id)
Tagging.create!(tag_id: massage.id, biz_id: earthbody.id)
Tagging.create!(tag_id: skin_care.id, biz_id: earthbody.id)

  taggings1 = Tagging.create!(tag_id: korean.id, biz_id: biz1.id)
  taggings2 = Tagging.create!(tag_id: american.id, biz_id: biz2.id)
  taggings3 = Tagging.create!(tag_id: ramen.id, biz_id: biz3.id)
  taggings4 = Tagging.create!(tag_id: ramen.id, biz_id: biz4.id)
  taggings5 = Tagging.create!(tag_id: noddles.id, biz_id: biz4.id)
  taggings6 = Tagging.create!(tag_id: coffee_tea.id, biz_id: biz5.id)
  taggings7 = Tagging.create!(tag_id: bubble_tea.id, biz_id: biz5.id)
  taggings8 = Tagging.create!(tag_id: bubble_tea.id, biz_id: biz6.id)
  taggings9 = Tagging.create!(tag_id: cafes.id, biz_id: biz6.id)
  taggings10 = Tagging.create!(tag_id: sushi_bars.id, biz_id: biz7.id)
  taggings11 = Tagging.create!(tag_id: japaness.id, biz_id: biz7.id)
  taggings12 = Tagging.create!(tag_id: japaness.id, biz_id: biz8.id)
  taggings13 = Tagging.create!(tag_id: sushi_bars.id, biz_id: biz8.id)
  taggings14 = Tagging.create!(tag_id: seafood.id, biz_id: biz8.id)
