
  biz1 = Biz.find_by_name('Cocobang')
  biz2 = Biz.find_by_name('Homeroom')
  biz3 = Biz.find_by_name('Ushi Taro')
  biz4 = Biz.find_by_name('Mensho Tokyo')
  biz5 = Biz.find_by_name('Boba Guys')
  biz6 = Biz.find_by_name('Urban Rital')
  biz7 = Biz.find_by_name("Ryoko's")
  biz8 = Biz.find_by_name('Saru Sushi Bar')
  user1 = User.find_by(email: "1@gmail.com")
  user2 = User.find_by(email: "2@gmail.com")
  user3 = User.find_by(email: "3@gmail.com")
  user4 = User.find_by(email: "4@gmail.com")
  user5 = User.find_by(email: "5@gmail.com")
  user6 = User.find_by(email: "6@gmail.com")
  user7 = User.find_by(email: "7@gmail.com")
  user8 = User.find_by(email: "8@gmail.com")
  user9 = User.find_by(email: "9@gmail.com")
  user10 = User.find_by(email: "10@gmail.com")
  user11 = User.find_by(email: "11@gmail.com")
  user12 = User.find_by(email: "12@gmail.com")
  user13 = User.find_by(email: "13@gmail.com")
  user14 = User.find_by(email: "14@gmail.com")
  user15 = User.find_by(email: "15@gmail.com")

  up1 = Upload.create(user_id: user1.id, biz_id: biz1.id)
  up1.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img1.jpg"), filename:"biz1_img1.jpg")
  up2 = Upload.create(user_id: user2.id, biz_id: biz1.id)
  up2.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img2.jpg"), filename:"biz1_img2.jpg")
  up3 = Upload.create(user_id: user3.id, biz_id: biz1.id)
  up3.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img3.jpg"), filename:"biz1_img3.jpg")
  up4 = Upload.create(user_id: user4.id, biz_id: biz1.id)
  up4.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img4.jpg"), filename:"biz1_img4.jpg")
  up5 = Upload.create(user_id: user5.id, biz_id: biz1.id)
  up5.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img5.jpg"), filename:"biz1_img5.jpg")
  up6 = Upload.create(user_id: user6.id, biz_id: biz1.id)
  up6.photo.attach(io: File.open("./app/assets/images/yeep_img/biz1_img6.jpg"), filename:"biz1_img6.jpg")

  up7 = Upload.create(user_id: user3.id, biz_id:biz2.id)
  up7.photo.attach(io: File.open("./app/assets/images/yeep_img/biz2_img1.jpg"), filename:"biz2_img1.jpg")
  up8 = Upload.create(user_id: user4.id, biz_id:biz2.id)
  up8.photo.attach(io: File.open("./app/assets/images/yeep_img/biz2_img2.jpg"), filename:"biz2_img2.jpg")
  up9 = Upload.create(user_id: user5.id, biz_id:biz2.id)
  up9.photo.attach(io: File.open("./app/assets/images/yeep_img/biz2_img3.jpg"), filename:"biz2_img3.jpg")
  up10 = Upload.create(user_id: user6.id, biz_id:biz2.id)
  up10.photo.attach(io: File.open("./app/assets/images/yeep_img/biz2_img4.jpg"), filename:"biz2_img4.jpg")

  up11 = Upload.create(user_id: user1.id, biz_id:biz3.id)
  up11.photo.attach(io: File.open("./app/assets/images/yeep_img/biz3_1.jpg"), filename:"biz3_1.jpg")
  up12 = Upload.create(user_id: user2.id, biz_id:biz3.id)
  up12.photo.attach(io: File.open("./app/assets/images/yeep_img/biz3_2.jpg"), filename:"biz3_2.jpg")
  up13 = Upload.create(user_id: user3.id, biz_id:biz3.id)
  up13.photo.attach(io: File.open("./app/assets/images/yeep_img/biz3_3.jpg"), filename:"biz3_3.jpg")
  up13 = Upload.create(user_id: user4.id, biz_id:biz3.id)
  up13.photo.attach(io: File.open("./app/assets/images/yeep_img/biz3_4.jpg"), filename:"biz3_4.jpg")

  up14 = Upload.create(user_id: user5.id, biz_id:biz4.id)
  up14.photo.attach(io: File.open("./app/assets/images/yeep_img/biz4_1.jpg"), filename:"biz4_1.jpg")
  up15 = Upload.create(user_id: user6.id, biz_id:biz4.id)
  up15.photo.attach(io: File.open("./app/assets/images/yeep_img/biz4_2.jpg"), filename:"biz4_2.jpg")
  up16 = Upload.create(user_id: user7.id, biz_id:biz4.id)
  up16.photo.attach(io: File.open("./app/assets/images/yeep_img/biz4_3.jpg"), filename:"biz4_3.jpg")
  up17 = Upload.create(user_id: user8.id, biz_id:biz4.id)
  up17.photo.attach(io: File.open("./app/assets/images/yeep_img/biz4_4.jpg"), filename:"biz4_4.jpg")

  up18 = Upload.create(user_id: user1.id, biz_id:biz5.id)
  up18.photo.attach(io: File.open("./app/assets/images/yeep_img/biz5_1.jpg"), filename:"biz5_1.jpg")
  up19 = Upload.create(user_id: user2.id, biz_id:biz5.id)
  up19.photo.attach(io: File.open("./app/assets/images/yeep_img/biz5_2.jpg"), filename:"biz5_2.jpg")
  up20 = Upload.create(user_id: user3.id, biz_id:biz5.id)
  up20.photo.attach(io: File.open("./app/assets/images/yeep_img/biz5_3.jpg"), filename:"biz5_3.jpg")
  up21 = Upload.create(user_id: user4.id, biz_id:biz5.id)
  up21.photo.attach(io: File.open("./app/assets/images/yeep_img/biz5_4.jpg"), filename:"biz5_4.jpg")

  up22 = Upload.create(user_id: user1.id, biz_id:biz6.id)
  up22.photo.attach(io: File.open("./app/assets/images/yeep_img/biz6_1.jpg"), filename:"biz6_1.jpg")
  up23 = Upload.create(user_id: user2.id, biz_id:biz6.id)
  up23.photo.attach(io: File.open("./app/assets/images/yeep_img/biz6_2.jpg"), filename:"biz6_2.jpg")
  up24 = Upload.create(user_id: user3.id, biz_id:biz6.id)
  up24.photo.attach(io: File.open("./app/assets/images/yeep_img/biz6_3.jpg"), filename:"biz6_3.jpg")
  up25 = Upload.create(user_id: user4.id, biz_id:biz6.id)
  up25.photo.attach(io: File.open("./app/assets/images/yeep_img/biz6_4.jpg"), filename:"biz6_4.jpg")

  up26 = Upload.create(user_id: user1.id, biz_id:biz7.id)
  up26.photo.attach(io: File.open("./app/assets/images/yeep_img/biz7_1.jpg"), filename:"biz7_1.jpg")
  up27 = Upload.create(user_id: user2.id, biz_id:biz7.id)
  up27.photo.attach(io: File.open("./app/assets/images/yeep_img/biz7_2.jpg"), filename:"biz7_2.jpg")
  up28 = Upload.create(user_id: user3.id, biz_id:biz7.id)
  up28.photo.attach(io: File.open("./app/assets/images/yeep_img/biz7_3.jpg"), filename:"biz7_3.jpg")
  up29 = Upload.create(user_id: user4.id, biz_id:biz7.id)
  up29.photo.attach(io: File.open("./app/assets/images/yeep_img/biz7_4.jpg"), filename:"biz7_4.jpg")

  up30 = Upload.create(user_id: user1.id, biz_id:biz8.id)
  up30.photo.attach(io: File.open("./app/assets/images/yeep_img/biz8_1.jpg"), filename:"biz8_1.jpg")
  up31 = Upload.create(user_id: user2.id, biz_id:biz8.id)
  up31.photo.attach(io: File.open("./app/assets/images/yeep_img/biz8_2.jpg"), filename:"biz8_2.jpg")
  up32 = Upload.create(user_id: user3.id, biz_id:biz8.id)
  up32.photo.attach(io: File.open("./app/assets/images/yeep_img/biz8_3.jpg"), filename:"biz8_3.jpg")
  up33 = Upload.create(user_id: user4.id, biz_id:biz8.id)
  up33.photo.attach(io: File.open("./app/assets/images/yeep_img/biz8_4.jpg"), filename:"biz8_4.jpg")
